# Generated by Django 2.1.7 on 2019-04-27 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_ip', models.CharField(max_length=64)),
                ('site_path', models.CharField(max_length=128)),
                ('postsite_msg', models.CharField(max_length=128, null=True)),
                ('current_version', models.CharField(max_length=64, null=True)),
                ('version_info', models.CharField(max_length=512, null=True)),
                ('author', models.CharField(max_length=64, null=True)),
                ('upcode_date', models.CharField(max_length=64, null=True)),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Depend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depend_name', models.CharField(max_length=64)),
                ('depend_version', models.CharField(max_length=64, null=True)),
                ('install_script', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_version', models.CharField(max_length=64, null=True)),
                ('version_info', models.CharField(max_length=512, null=True)),
                ('author', models.CharField(max_length=64, null=True)),
                ('upcode_date', models.CharField(max_length=64, null=True)),
                ('CodePost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_code.CodePost')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=32, unique=True)),
                ('project_msg', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=64, unique=True)),
                ('site_msg', models.CharField(max_length=64, null=True)),
                ('site_url', models.CharField(max_length=128, unique=True)),
                ('site_depend', models.CharField(max_length=256, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_code.Project')),
            ],
        ),
        migrations.AddField(
            model_name='codepost',
            name='post_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_code.Site'),
        ),
    ]
