# Generated by Django 2.1.2 on 2018-12-03 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20181203_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='employmentdate',
            new_name='employeedate',
        ),
    ]
