# Generated by Django 2.1.2 on 2018-11-29 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('createdate', models.DateTimeField(blank=True, db_column='createDate', null=True)),
                ('createby', models.CharField(blank=True, db_column='createBy', max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('scope', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('fathercompany', models.IntegerField(blank=True, db_column='fatherCompany', null=True)),
            ],
            options={
                'db_table': 'company',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('manager', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('admin', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.IntegerField(blank=True, null=True)),
                ('fatherdepartment', models.IntegerField(blank=True, db_column='fatherDepartment', null=True)),
            ],
            options={
                'db_table': 'department',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Partproject',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('labour', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('startdate', models.DateTimeField(blank=True, db_column='startDate', null=True)),
                ('enddate', models.DateTimeField(blank=True, db_column='endDate', null=True)),
            ],
            options={
                'db_table': 'partproject',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('startdate', models.DateTimeField(blank=True, db_column='startDate', null=True)),
                ('enddate', models.DateTimeField(blank=True, db_column='endDate', null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'project',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('project', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CompanySafteyManage.Company')),
            ],
            options={
                'db_table': 'projectrole',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Subproject',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('startdate', models.DateTimeField(blank=True, db_column='startDate', null=True)),
                ('enddate', models.DateTimeField(blank=True, db_column='endDate', null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('constructor', models.CharField(blank=True, max_length=255, null=True)),
                ('labor', models.IntegerField(blank=True, db_column='Labor', null=True)),
                ('project', models.ForeignKey(blank=True, db_column='project', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CompanySafteyManage.Project')),
            ],
            options={
                'db_table': 'subproject',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='partproject',
            name='subproject',
            field=models.ForeignKey(blank=True, db_column='subProject', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CompanySafteyManage.Subproject'),
        ),
    ]
