# Generated by Django 2.1.2 on 2018-12-03 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CompanySafteyManage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partproject',
            name='subproject',
        ),
        migrations.RemoveField(
            model_name='subproject',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectrole',
            name='company',
        ),
        migrations.AddField(
            model_name='department',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='projectrole',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CompanySafteyManage.Department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CompanySafteyManage.Company'),
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CompanySafteyManage.Project'),
        ),
        migrations.DeleteModel(
            name='Partproject',
        ),
        migrations.DeleteModel(
            name='Subproject',
        ),
    ]
