# Generated by Django 2.1.7 on 2019-04-27 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_rbac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=64, unique=True)),
                ('msg', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.CharField(max_length=64, unique=True)),
                ('device_type', models.CharField(max_length=64)),
                ('port', models.CharField(max_length=64)),
                ('msg', models.CharField(max_length=64, null=True)),
                ('hostname', models.CharField(max_length=64, null=True)),
                ('in_ip', models.CharField(max_length=64, null=True)),
                ('os_type', models.CharField(max_length=64, null=True)),
                ('service_type', models.CharField(max_length=64, null=True)),
                ('os_version', models.CharField(max_length=64, null=True)),
                ('mem_total', models.CharField(max_length=64, null=True)),
                ('mem_swap', models.CharField(default='0', max_length=32)),
                ('cpu_type', models.CharField(max_length=64, null=True)),
                ('cpu_num', models.CharField(max_length=16, null=True)),
                ('mount_home', models.CharField(max_length=128, null=True)),
                ('mount_root', models.CharField(max_length=128, null=True)),
                ('mount_alidata', models.CharField(max_length=128, null=True)),
                ('kernel', models.CharField(max_length=64, null=True)),
                ('status', models.CharField(max_length=16, null=True)),
                ('addTime', models.DateTimeField(auto_now_add=True)),
                ('host_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cmdb.HostGroup')),
            ],
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idc_name', models.CharField(max_length=64, unique=True)),
                ('msg', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_user', models.CharField(max_length=64, unique=True)),
                ('login_passwd', models.CharField(max_length=256)),
                ('private_key', models.CharField(max_length=2048, null=True)),
                ('people', models.ForeignKey(on_delete=None, to='app_rbac.UserInfo')),
            ],
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='idc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cmdb.IDC'),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='remote_user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app_cmdb.LoginUser'),
        ),
    ]
