# Generated by Django 2.1.7 on 2019-04-27 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perms_title', models.CharField(max_length=64)),
                ('perms_url', models.CharField(max_length=64)),
                ('perms_type', models.CharField(max_length=32)),
                ('pmenu_id', models.CharField(max_length=32, null=True)),
                ('perms_num', models.CharField(max_length=32, null=True)),
                ('perms_icon', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(max_length=64, unique=True)),
                ('role_msg', models.CharField(max_length=128, null=True)),
                ('perms', models.ManyToManyField(to='app_rbac.Permission')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=128, null=True)),
                ('status', models.CharField(default='离线', max_length=64)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_rbac.Role')),
                ('user', models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
