# Generated by Django 2.1.7 on 2019-04-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_ip', models.CharField(max_length=32)),
                ('hostname', models.CharField(max_length=64, null=True)),
                ('user_name', models.CharField(max_length=64)),
                ('start_time', models.CharField(max_length=64)),
                ('audit_log', models.TextField()),
            ],
        ),
    ]
