# Generated by Django 2.1.7 on 2019-05-01 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CMDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=64, unique=True)),
                ('device_type', models.CharField(choices=[(0, 'worker'), (1, 'hava_server'), (2, 'jenkins_server')], default=0, max_length=10)),
                ('port', models.CharField(max_length=64)),
                ('hostname', models.CharField(max_length=64, null=True)),
                ('status', models.BooleanField(default=True)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('rsa_pub', models.BooleanField()),
                ('authentication', models.CharField(choices=[('0', 'sess'), ('1', 'password')], max_length=10)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.Group')),
            ],
        ),
    ]
