# Generated by Django 2.1.7 on 2019-05-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmdb',
            name='rsa_pub',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
